### ISSUE TITLE
Update Lab 5.1 Hint

### ISSUE THREAD

**Issue by schlapzz** [acend/argocd-basics-training#278]
```
Info
Values files must be in the same git repository as the Helm chart. The files can be in a different location in which case it can be accessed using a relative path relative to the root directory of the Helm chart.
```

This problem is solved since ArgoCD v2.6. ArgoCD Supports multiple Sources and References

e.g.

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
spec:
  sources:
  - repoURL: 'https://prometheus-community.github.io/helm-charts'
    chart: prometheus
    targetRevision: 15.7.1
    helm:
      valueFiles:
      - $values/charts/prometheus/values.yaml
  - repoURL: 'https://git.example.gom/org/value-files.git'
    targetRevision: dev
    ref: values
```
